apiVersion: v1
kind: Secret
metadata:
    namespace: todo-ns
    name: postgres-secret
data:
    password: ENC[AES256_GCM,data:AjJOXp3UCRDgWoNHwDC2jTDB9hhq2GtTL2muKE5HEv4=,iv:zguCtDDv+ER050aKpUPGUkN7PTDzU0dqO2X+OkezF+0=,tag:NRPyslPjTJGXWLaPrXSXeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r25un5hpw3gcyaxwgmtn2ca86e76zf27hsadwc5plydwjr0ssdds2f2j70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWG93V3BFKzZTNWlXNElB
            Slg2UFNNZkZmWjIzU040UktEaVAvVDFnempRClhTY3FwY1VyK0JXVXl6eExDYnJ5
            MnNNWldaaXJGTWJGaEoyMlppRmVUbjAKLS0tIEFZT0F2Ky9qTHNFQnlJanVYaEJi
            L05KNGYwaVFMaVBIVVJJNzdjdm5RN1UKwNICX33y/+F+25hqpkL8CbIaktpViJDR
            akD5yVvmfFzlWfsTjVjGtolu6vA+41g2GHDBrz3CAChTbe5Gu0y9tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-08T00:21:26Z"
    mac: ENC[AES256_GCM,data:MCXrfhfvzfoUdpO33RQlOf48qQnamZ++hso3fTvynEHkVCYhzI+OW0Z2ULzN9v+svnYjIy/MTlqcMaUKkskv/41fUzUIdxzEhNSKhXg2fDkH60ED0uoIaRJrvhrBfHoS/V9tIRA2lqWick07aRAv/aoFgqk6HZ7pVFgmJXIXcq4=,iv:uCmnwbPbVhfxieIX1xe40uuu8nx9zFTt1fJ+LmB5pHg=,tag:cwrBxAQQOLS+iotddPLeZw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
