apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: writer
          image: dogamak/hy-kubernetes-log-writer:v1
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-volume
            mountPath: /data
          env:
          - name: DATA_PATH
            value: /data
        - name: reader
          image: dogamak/hy-kubernetes-log-reader:v1
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-volume
            path: /data
          env:
          - name: DATA_PATH
            value: /data
