apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-ns
  name: todo-claim
spec:
  storageClassName: local-path
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
