apiVersion: v1
kind: ConfigMap
metadata:
  namespace: log-ping-pong
  name: pong-config-map
data:
  config: |
    [server]
    port = 8080

    [database]
    host = "postgres-svc"
    port = 5432
    database = "production"
    user = "postgres"
