apiVersion: v1
kind: Service
metadata:
  namespace: log-ping-pong
  name: log-output-svc
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

