apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-ping-pong
  name: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: dogamak/hy-kubernetes-ping-pong-app:v4
          imagePullPolicy: Always
          env:
            - name: PONG_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /config.toml
              subPath: config
      volumes:
        - name: config-volume
          configMap:
            name: pong-config-map
