apiVersion: v1
kind: ConfigMap
metadata:
  namespace: todo-ns
  name: todo-config-map
data:
  config: |
    [http]
    port = 8080

    [app]
    data_path = "/data"

    [database]
    host = "postgres-svc"
    port = 5432
    database = "production"
    user = "postgres"
