name: Release project (Exercise 3.03)

on:
  push:
    paths:
      - 'exercise_3.03/**'
      - '.github/workflows/exercise_3_03.yaml'

env:
  EXERCISE: "exercise_3.03"
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: hy-kube-cluster
  GKE_ZONE: europe-north1-b
  FRONTEND_IMAGE: hy-kubernetes-todo-app-frontend
  BACKEND_IMAGE: hy-kubernetes-todo-app-backend
  DAILY_TODO_JOB_IMAGE: hy-kubernetes-todo-app-daily-todo-job

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_id: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build Frontend
        run: docker build --tag "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" frontend

      - name: Build Backend
        run: docker build --tag "gcr.io/$PROJECT_ID/$BACKEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" --target todo-app backend

      - name: Build Daily Todo Job
        run: docker build --tag "gcr.io/$PROJECT_ID/$DAILY_TODO_JOB_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" --target daily-todo-job daily-todo-job

      - name: Publish Frontend
        run: docker push "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Publish Backend
        run: docker push "gcr.io/$PROJECT_ID/$BACKEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Publish Daily Todo Job
        run: docker push "gcr.io/$PROJECT_ID/$DAILY_TODO_JOB_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Deploy
        run: |-
          kustomize edit set image "todo-app/frontend=gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
          kustomize edit set image "todo-app/backend=gcr.io/$PROJECT_ID/$BACKEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
          kustomize edit set image "todo-app/daily-todo-job=gcr.io/$PROJECT_ID/$DAILY_TODO_JOB_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
          kustomize build frontend/manifests manifests | kubectl apply -f -
          kubectl rollout status deployment $FRONTEND_IMAGE
          kubectl get services -o wide
